name: Draft release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**.zig'
      - '**/build.zig.zon'
      - 'ci/get_version.py'
      - '.github/workflows/draft-release.yml'

  pull_request:
    branches:
      - main
    paths:
      - '**.zig'
      - '**/build.zig.zon'
      - 'ci/get_version.py'
      - '.github/workflows/draft-release.yml'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Setup uv
        uses: astral-sh/setup-uv@v8.2.0

      - name: Fetch version from build.zig.zon
        id: fetch_version
        run: |
          uv run ci/get_version.py
          echo version=$(uv run ci/get_version.py) >> $GITHUB_OUTPUT

      - name: Release
        if: ${{ !contains(fromJSON('["push", "pull_request"]'), github.event_name) }}
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.fetch_version.outputs.version }}
          draft: true
          generate_release_notes: true
