name: zig build test

on:
  push:
    branches:
      - main
    paths:
      - '**/*.zig'
      - '**/build.zig.zon'
      - '.github/workflows/zig-build-test.yml'

  pull_request:
    branches:
      - main
    paths:
      - '**/*.zig'
      - '**/build.zig.zon'
      - '.github/workflows/zig-build-test.yml'

  schedule:
    - cron: "0 0 * * Sat"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        zig-version: 
          - "0.14.0"
          - "0.14.1"
          - "0.15.1"
          - master
    
    name: Build and Test
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
        with:
          version: ${{ matrix.zig-version }}

      - name: Run linter
        run: |
          wget https://github.com/DonIsaac/zlint/releases/download/v0.7.9/zlint-linux-x86_64 -O zlint
          chmod +x zlint
          ./zlint --deny-warnings

      - name: Run unit tests
        run: zig build test

      - name: Run integration tests
        run: |
          cd tests
          zig build test
